GET / HTTP/1.1
Host: localhost:8080

###

# sample get request
GET /get-tokens?user-uuid=3a64147b-fdac-4e8b-9869-0fbb7c4c737b HTTP/1.1
Host: localhost:8080

###

# sample refresh request
# substitute the tokens you got from previous request
POST /refresh-tokens HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
	"access_token":"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIzYTY0MTQ3Yi1mZGFjLTRlOGItOTg2OS0wZmJiN2M0YzczN2IiLCJleHAiOjE2Mjk1NjIxMjl9.G4E8OkGVydYwi-a-HOoOdgLfh2hLyiXiacMU-C-cA-H6R3zzxDHbWPzEMxEYxQxLFCfERE4fGP450k0oIy_cQQ",
	"refresh_token":"U2F0IEF1ZyAyMSAyMjowNjoxOSArMDUgMjAyMS5KidM4eb9xzVmVxA3EzzzMWansiGAkg1YSE_fBuwjrhEPbpkuJ2HLR2Lu1twDyW_JowRIKjskt1LiJu0KQ-kLS"
}


###